server:
  port: 8080
  servlet:
    context-path: /im_bird_sys
spring:
  datasource:
    name: im_bird_sys
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/im_bird_sys?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    filters: stat    #监控统计
    initial-size: 5  #初始化连接数
    max-idld: 10     #最大空闲连接数
    min-idld: 1      #最小空闲连接数
    max-wait: 60000  #连接超时时间
    time-between-eviction-runs-millis: 60000 #间隔多久检查一次需要关闭的空闲连接
    validation-query: SELECT 'x'  #验证连接是否有效
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 39.106.167.46:22122